# A generic, single database configuration for Alembic.

[alembic]
# path to migration scripts
script_location = app/database/migrations

# template used to generate new migration files
# file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s

# prepend VXX_ to migrations, or use default
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters to write to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported from current directory
# prepend_sys_path = .

# version location specification; this defaults
# to migrations/versions.  when using multiple version
# directories, paths must be separated by colons.
version_locations = app/database/migrations/versions

# version path separator; as above, this defaults to ';'
# version_path_separator = ;

# database URL is set dynamically in env.py from environment variables
sqlalchemy.url = sqlite:///./caja_facil.db

[post_write_hooks]
# post_write_hooks defines scripts or tools that run after a revision is created.
# example: formatting code using black
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = REVISION_SCRIPT_FILE

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
