"""consolidate_product_table

Revision ID: 18012e53eca6
Revises: cbfe8faf79d5
Create Date: 2026-07-19 15:49:55.763238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18012e53eca6'
down_revision: Union[str, None] = 'cbfe8faf79d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               nullable=False)
        batch_op.alter_column('brand_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               nullable=False)
        batch_op.alter_column('unit_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_product_unit', 'unit', ['unit_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_product_brand', 'brand', ['brand_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_product_category', 'category', ['category_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_product_company', 'company', ['company_id'], ['id'], ondelete='RESTRICT')



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_unit', type_='foreignkey')
        batch_op.drop_constraint('fk_product_brand', type_='foreignkey')
        batch_op.drop_constraint('fk_product_category', type_='foreignkey')
        batch_op.drop_constraint('fk_product_company', type_='foreignkey')
        batch_op.alter_column('unit_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('brand_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)



    # ### end Alembic commands ###
