"""add_missing_foreign_keys

Revision ID: 3550d9ef68a2
Revises: 18012e53eca6
Create Date: 2026-07-20 13:44:49.459994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3550d9ef68a2'
down_revision: Union[str, None] = '18012e53eca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_brand_company', 'company', ['company_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_category_company', 'company', ['company_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_category_parent', 'category', ['parent_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_unit_company', 'company', ['company_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_constraint('fk_unit_company', type_='foreignkey')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_parent', type_='foreignkey')
        batch_op.drop_constraint('fk_category_company', type_='foreignkey')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_constraint('fk_brand_company', type_='foreignkey')
    # ### end Alembic commands ###
